# Generated by Django 5.0.1 on 2024-01-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_name', models.CharField(verbose_name='Название')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questions', verbose_name='Название')),
            ],
        ),
    ]
