# Generated by Django 5.0.1 on 2024-01-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_categories_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='Правильный вариант ответа'),
        ),
    ]
